version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/projects/design-system'
      - '/demo'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
